### PR TITLE
Fix: include NRIRayTracing.h in NRIWrapperVK.h

### PR DESCRIPTION
**Pull request by MaxFreedomPollard**
`NRIWrapperVK.h` does not compile unless `NRIRayTracing.h` was included before it:

```cpp
#include "NRI.h"
#include "Extensions/NRIWrapperVK.h"
```

```
Include/Extensions/NRIWrapperVK.h:110:9: error: unknown type name 'AccelerationStructureBits'; did you mean 'AccelerationStructure'?
  110 |     Nri(AccelerationStructureBits) flags;
```

`AccelerationStructureVKDesc::flags` is an `AccelerationStructureBits`, which is declared in `NRIRayTracing.h`. `NRIWrapperD3D12.h` already includes that header, so this does the same for the VK wrapper. The `NriForwardStruct(AccelerationStructure)` that stood in for the include is no longer needed. It was also a second typedef of the same name in C whenever both headers were included, which `-std=c99 -pedantic` warns about.

Checked with clang: the snippet above now compiles as C++17 and as C11 with `-Wall -Wextra -Werror`, in either include order, and every header in `Include/Extensions` compiles on its own after `NRI.h`.

### CODE REVIEW

**Comment by dzhdanNV** [comment]
Agreed. Thanks! Merged!
